Repository SPbSTU-OPD-Palihindron-team/Open-space-map-constructor-FrontEnd, pull requests merged in 2022-05, with the labels that each got.

#35 Right-slide navigation menu component
  package-lock.json
  package.json
  src/App.tsx
  src/components/RightMenu/InformationOfEmployees.tsx
  src/components/RightMenu/RightSlideMenu.css
  src/components/RightMenu/RightSlideMenu.tsx
  src/components/RightMenu/Search.tsx
  src/stores/Employees.ts
Labels: enhancement

#37 Fix display right slide menu
  src/App.tsx
  src/components/LeftSlideMenu.tsx
  src/components/RightMenu/RightSlideMenu.tsx
  src/components/RightSlideMenu/InformationOfEmployees.tsx
  src/components/RightSlideMenu/RightSlideMenu.css
  src/components/RightSlideMenu/RightSlideMenu.tsx
  src/components/RightSlideMenu/Search.tsx
  src/stores/EmployeesStore.ts
Labels: bug

#38 Change styles for correct displaying of menu.
  src/components/RightSlideMenu/RightSlideMenu.css
Labels: bug

#40 Creating of primitives(walls)
  package.json
  src/App.tsx
  src/assets/images/icons/icons.ts
  src/assets/images/icons/line.png
  src/assets/images/icons/tools.ts
  src/components/Canvas/Canvas.tsx
  src/components/Canvas/CanvasGrid.tsx
  src/components/Canvas/CanvasItems.tsx
  src/components/Canvas/CanvasWalls.tsx
  src/components/CanvasItems.tsx
  src/components/LeftSlideMenu.tsx
  src/stores/CanvasStore.ts
Labels: enhancement

#41 Navigation bar component
  src/App.tsx
  src/components/NavBar/NavBar.css
  src/components/NavBar/NavBar.tsx
  src/components/NavBar/NavBarIcon.tsx
  src/components/NavBar/NavBarInformation.tsx
  src/components/NavBar/NavBarSwitch.tsx
  src/components/NavBar/SelectBuilding.tsx
  src/components/RightSlideMenu/RightSlideMenu.css
  src/stores/CanvasStore.ts
Labels: enhancement

#47 Back forward action processing
  src/components/Canvas/Canvas.tsx
  src/components/Canvas/CanvasItems.tsx
  src/components/NavBar/NavBarIcon.tsx
  src/stores/CanvasStore.ts
  src/stores/undo_redo/Action.ts
  src/stores/undo_redo/UndoRedoAdapter.ts
  src/stores/undo_redo/actions/AddItem.ts
  src/stores/undo_redo/actions/DeleteItem.ts
  src/stores/undo_redo/actions/DragItem.ts
Labels: enhancement

#54 Modification of canvas elements
  src/App.tsx
  src/components/Canvas/Canvas.tsx
  src/components/Canvas/CanvasItems.tsx
  src/components/Canvas/URLImage.tsx
  src/stores/CanvasStore.ts
  src/stores/undo_redo/actions/TransformItem.ts
Labels: bug, enhancement

#58 Correct display of page elements
  documents/reference/api.yaml
  src/components/Canvas/Canvas.tsx
  src/components/LeftSlideMenu.tsx
  src/components/LeftSlideMenu/LeftSlideMenu.css
  src/components/LeftSlideMenu/LeftSlideMenu.tsx
  src/components/NavBar/NavBar.tsx
  src/components/NavBar/NavBarIcon.tsx
  src/components/NavBar/NavBarSwitch.tsx
Labels: bug

#59 Authorization modal window component.
  src/App.tsx
  src/components/AuthModalWindow/AuthModalWindow.css
  src/components/AuthModalWindow/AuthModalWindow.tsx
  src/components/AuthModalWindow/CreateAccount.tsx
  src/components/AuthModalWindow/LogIn.tsx
  src/components/NavBar/NavBarInformation.tsx
  src/hooks/useInput.tsx
  src/hooks/useValidation.tsx
  src/index.tsx
  src/stores/AuthModalWindowStore.ts
Labels: enhancement

#62 Implement adding of floor and building
  src/components/NavBar/SelectBuilding.tsx
  src/components/RightSlideMenu/InformationOfEmployees.tsx
  src/components/RightSlideMenu/RightSlideMenu.tsx
  src/components/RightSlideMenu/Search.tsx
  src/stores/BuildingsStore.ts
  src/stores/EmployeesStore.ts
  src/stores/FloorsStore.ts
Labels: enhancement
